### ISSUE TITLE
Question: update verbosity.

### ISSUE THREAD

**Issue by katsika** [getantibody/antibody#223] opened 2018-03-16 09:03 UTC
Hey, had a quick look at code and can't see anything that would print information about updated repositories. Does antibody quietly updates repositories? If so, is there a chance some information could be printed to indicate that update was performed?

Thanks.

**Comment by felipe19930** [comment] 2018-03-17 02:16
I really like the verbosity that `git pull` gives me, and I think something like that would be great for antibody. But probably most people wouldn't like that, specially when you have a considerable amount of plugins. So I think something like `antibody update -v` would be really nice.

**Comment by caarlos0** [comment] 2018-03-17 12:24
duplicate of #203

**Closed** 2018-03-17 12:24 UTC
Labels: duplicate
